hide-cursor-when-typing = true
padding-x = 10
padding-y = [10,10]
theme = "ostrea_light"
confirm-before-quit = false

[cursor]
shape = 'block'
blinking = false

[editor]
program = "vim"
args = []

use-fork = true

[renderer]
performance = "High"
backend = "Automatic"

[navigation]
use-split = true
clickable = true
mode = "Bookmark"
# mode = "BottomTab"

[fonts]
size = 18
features = []
family="JetBrains Mono"
extras = [{ family = "KoPubWorldDotum_Pro" }, {family= "Noto Color Emoji"}]

[fonts.emoji]
family = "Noto Color Emoji"

[fonts.regular]
family="JetBrains Mono"
style = "Normal"

[fonts.bold]
family="JetBrains Mono"
style = "Normal"
weight = 800

[fonts.italic]
family="JetBrains Mono"
style = "Italic"

[fonts.bold-italic]
family="JetBrains Mono"
style = "Italic"
weight = 800

[fonts.ui]
family = "JetBrains Mono"
weight = 800
