[colors]
background                      = '#DDE0CA'
dim-foreground                  = '#2E2B3B'
light-foreground                = '#2E2B3B'
foreground                      = '#2E2B3B'

black                           = '#2E2B3B'
red                             = '#8C4C61'
green                           = '#4C6E38'
yellow                          = '#77601B'
blue                            = '#4F5F96'
magenta                         = '#765286'
cyan                            = '#116D89'
white                           = '#DDE0CA'

dim-black                       = '#2E2B3B'
dim-red                         = '#8C4C61'
dim-green                       = '#4C6E38'
dim-yellow                      = '#77601B'
dim-blue                        = '#4F5F96'
dim-magenta                     = '#765286'
dim-cyan                        = '#116D89'
dim-white                       = '#DDE0CA'

light-black                     = '#2E2B3B'
light-red                       = '#8C4C61'
light-green                     = '#4C6E38'
light-yellow                    = '#77601B'
light-blue                      = '#4F5F96'
light-magenta                   = '#765286'
light-cyan                      = '#116D89'
light-white                     = '#DDE0CA'

cursor                          = '#3B3552'
vi-cursor                       = '#116D89'

tabs                            = '#3A3D1D'
tabs-active                     = '#3B3552'
tabs-active-highlight           = '#3B3552'
tabs-active-foreground          = '#DDE0CA'
tabs-foreground                 = '#2E2B3B' 
bar                             = '#98CBAC' 

search-match-background         = '#DCB58D'
search-match-foreground         = '#2E2B3B'
search-focused-match-background = '#DCACCD'
search-focused-match-foreground = '#2E2B3B'

selection-background            = '#9AC2E9'
selection-foreground            = '#2E2B3B'
