[colors]
background                      = '#2E2B3B'
dim-foreground                  = '#DDE0CA'
light-foreground                = '#DDE0CA'
foreground                      = '#DDE0CA'

black                           = '#2E2B3B'
red                             = '#CD869C'
green                           = '#86AB72'
yellow                          = '#B49C5A'
blue                            = '#889BD7'
magenta                         = '#B38DC5'
cyan                            = '#5AAAC8'
white                           = '#DDE0CA'

dim-black                       = '#2E2B3B'
dim-red                         = '#CD869C'
dim-green                       = '#86AB72'
dim-yellow                      = '#B49C5A'
dim-blue                        = '#889BD7'
dim-magenta                     = '#B38DC5'
dim-cyan                        = '#5AAAC8'
dim-white                       = '#DDE0CA'

light-black                     = '#2E2B3B'
light-red                       = '#CD869C'
light-green                     = '#86AB72'
light-yellow                    = '#B49C5A'
light-blue                      = '#889BD7'
light-magenta                   = '#B38DC5'
light-cyan                      = '#5AAAC8'
light-white                     = '#DDE0CA'

cursor                          = '#CDD1AC'
vi-cursor                       = '#57B0A0'

tabs                            = '#CEC8EC'
tabs-active                     = '#CDD1AC'
tabs-active-highlight           = '#CDD1AC'
tabs-active-foreground          = '#2E2B3B' 
tabs-foreground                 = '#DDE0CA' 
bar                             = '#215238' 

search-match-background         = '#603F19'
search-match-foreground         = '#DDE0CA'
search-focused-match-background = '#5F3855'
search-focused-match-foreground = '#DDE0CA' 

selection-background            = '#254A6B'
selection-foreground            = '#DDE0CA'
