[colors]
background                      = '#3B3849'
dim-foreground                  = '#EEF1DA' 
foreground                      = '#DEE0CA'
light-foreground                = '#CED0BA'

black                           = '#DEE0CA'
red                             = '#EAA9BB'
green                           = '#A8CA96'
yellow                          = '#D2BC82'
blue                            = '#A9BCF2'
magenta                         = '#D1AFE2'
cyan                            = '#84C9E5'
white                           = '#3B3849'

dim-black                       = '#EEF1DA'
dim-red                         = '#EAA9BB'
dim-green                       = '#A8CA96'
dim-yellow                      = '#D2BC82'
dim-blue                        = '#A9BCF2'
dim-magenta                     = '#D1AFE2'
dim-cyan                        = '#84C9E5'
dim-white                       = '#484557'

light-black                     = '#CED0BA'
light-red                       = '#EAA9BB'
light-green                     = '#A8CA96'
light-yellow                    = '#D2BC82'
light-blue                      = '#A9BCF2'
light-magenta                   = '#D1AFE2'
light-cyan                      = '#84C9E5'
light-white                     = '#2E2B3C'

cursor                          = '#CED0BA'
vi-cursor                       = '#82CFC0'

tabs                            = '#EFEBFF'
tabs-active                     = '#EEF1DA'
tabs-active-highlight           = '#EEF1DA'
tabs-active-foreground          = '#445282'
tabs-foreground                 = '#BEC0AA'
bar                             = '#484557'

search-match-background         = '#675317'
search-match-foreground         = '#DEE0CA'
search-focused-match-background = '#7A462E'
search-focused-match-foreground = '#DEE0CA'

selection-background            = '#555744'
selection-foreground            = '#DEDBF1' 
