[colors]
background                      = '#EEF0DA'
dim-foreground                  = '#2E2B3B' 
light-foreground                = '#2E2B3B'
foreground                      = '#2E2B3B'

black                           = '#EEF0DA'
red                             = '#8C4C61'
green                           = '#4C6E38'
yellow                          = '#77601B'
blue                            = '#4F5F96'
magenta                         = '#765286'
cyan                            = '#116D89'
white                           = '#474456'

dim-black                       = '#EEF0DA'
dim-red                         = '#8C4C61'
dim-green                       = '#4C6E38'
dim-yellow                      = '#77601B'
dim-blue                        = '#4F5F96'
dim-magenta                     = '#765286'
dim-cyan                        = '#116D89'
dim-white                       = '#2E2B3B'

light-black                     = '#474936'
light-red                       = '#8C4C61'
light-green                     = '#4C6E38'
light-yellow                    = '#77601B'
light-blue                      = '#4F5F96'
light-magenta                   = '#765286'
light-cyan                      = '#116D89'
light-white                     = '#2E2B3B'

cursor                          = '#474456'
vi-cursor                       = '#037365'

tabs                            = '#474936'
tabs-active                     = '#8D5135'
tabs-active-highlight           = '#ADDABE'
tabs-active-foreground          = '#EEF0DA'
tabs-foreground                 = '#EEF0DA'
bar                             = '#ADDABE'

search-match-background         = '#E8C7A4'
search-match-foreground         = '#2E2B3B'
search-focused-match-background = '#E8BFDB'
search-focused-match-foreground = '#2E2B3B'

selection-background            = '#AFD2F3'
selection-foreground            = '#2E2B3B' 
