"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$shell\
$directory\
$git_branch\
$git_commit\
$git_status\
$fill\
$cmd_duration\
$python\
$time\
$status
$character
"""
palette = 'even_light'

[palettes.even_light]
fg0           = "#DDE0CA"
bg0           = "#2E2B3B"
bg1           = "#CEC8EC"
red           = "#8C4C61"
green         = "#4C6E38"
yellow        = "#77601B"
blue          = "#4F5F96"
magenta       = "#765286"
syan          = "#116D89"

[palettes.even_dark]
fg0           = "#2E2B3B"
bg0           = "#DDE0CA"
bg1           = "#3A3D1D"
red           = "#CD869C"
green         = "#86AB72"
yellow        = "#B49C5A"
blue          = "#889BD7"
magenta       = "#B38DC5"
syan          = "#5AAAC8"


[python]
disabled       = false
symbol         = " "
version_format = '${raw}'
style          = 'bold fg:bg0 bg:bg1'
format         = '[ [$symbol](fg:bg0 bg:bg1)${version} (\($virtualenv\)) ]($style)'

[shell]
disabled       = false
bash_indicator = "bash"
zsh_indicator  = "%"
nu_indicator   = ""
style          = 'bold fg:fg0 bg:bg0'
format         = '[| $indicator ]($style)'

[fill]
symbol = ' '

[os]
disabled = false
style    = 'bold fg:fg0 bg:bg0'
format   = '[ $symbol ]($style)'

[os.symbols]
Arch     = ""
Gentoo   = ""
Linux    = ""
NixOS    = ""
Raspbian = ""
Void     = ""
Windows  = ""

[character]
disabled       = false
success_symbol = '[λ](bold green) '
error_symbol   = '[λ](bold red) '

[time]
disabled        = false
format          = '[  $time |]($style)'
style           = 'bold fg:fg0 bg:bg0'
time_format     = '%R'
utc_time_offset = 'local'

[cmd_duration]
min_time          = 0
show_milliseconds = true
style             = 'bold fg:bg0 bg:bg1'
format            = '[ $duration |]($style)'

[git_branch]
symbol            = ' '
style             = 'bold fg:bg0 bg:bg1'
truncation_length = 22
truncation_symbol = '…'
format            = '[| $symbol$branch(:$remote_branch)]($style)'

[git_commit]
commit_hash_length = 7
tag_symbol         = '󰓹 '
only_detached      = false
tag_disabled       = false
style              = 'bold fg:magenta bg:bg1'
format             = '[ $tag\($hash\)]($style)'

[git_status]
format      = "[$ahead_behind$all_status ](fg:bg0 bg:bg1)"
diverged    = "[  $ahead_count $behind_count](fg:magenta bg:bg1)"
ahead       = "[  $count](fg:blue bg:bg1)"
behind      = "[  $count](fg:red bg:bg1)"
conflicted  = "[ 󰵖 $count](fg:red bg:bg1)"
stashed     = "[ 󰦕 $count](fg:aqua bg:bg1)"
deleted     = "[  $count](fg:red bg:bg1)"
renamed     = "[  $count](fg:blue bg:bg1)"
modified    = "[  $count](fg:aqua bg:bg1)"
typechanged = "[ 󰴝 $count](fg:blue bg:bg1)"
staged      = "[ 󰗡 $count](fg:green bg:bg1)"
untracked   = "[ ◌ $count](fg:blue bg:bg1)"

[status]
disabled              = false
style                 = 'bold fg:fg0 bg:bg0'
symbol                = ' '
success_symbol        = ' '
not_executable_symbol = ' '
not_found_symbol      = ' '
sigint_symbol         = ' '
signal_symbol         = ' '
map_symbol            = true
format                = '[ $symbol$common_meaning$status$signal_name$signal_number ]($style)'

[directory]
read_only                 = " "
fish_style_pwd_dir_length = 2
style                     = 'bold fg:bg0 bg:bg1'
read_only_style           = 'bold fg:bg0 bg:bg1'
format                    = '[ $read_only($read_only_style)$path ]($style)'
