"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$shell\
$directory\
$git_branch\
$git_commit\
$git_status\
$fill\
$status\
$c\
$python\
$time\
$cmd_duration
$character
"""
palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
fg0       = '#282828'
bg0       = '#f2e5bc'
bg2      = '#d5c4a1'
light3      = '#bdae93'
light4      = '#a89984'
neutral_red    = '#cc241d'
neutral_green  = '#98971a'
neutral_yellow = '#d79921'
neutral_blue   = '#458588'
neutral_purple = '#b16286'
neutral_aqua   = '#689d6a'
neutral_orange = '#d65d0e'
faded_red      = '#9d0006'
faded_green    = '#79740e'
faded_yellow   = '#b57614'
faded_blue     = '#076678'
faded_purple   = '#8f3f71'
faded_aqua     = '#427b58'
faded_orange   = '#af3a03'

[c]
disabled = false
symbol = " "
version_format = "${raw}"
style = 'bold'
format = '[$symbol ($name(-$version))]($style)'

[python]
disabled = false
symbol = "󰌠 "
version_format = '${raw}'
format = '[${symbol}${version} (\($virtualenv\))]($style)'

[shell]
disabled = false
bash_indicator = "bash"
zsh_indicator = "%zsh"
nu_indicator = "nu"
style = 'bold fg:color_fg0 bg:color_blue'
format = '[$indicator  ]($style)'	

[fill]
symbol = ' '

[os]
disabled = false
style = 'bold fg:light0_soft bg:neutral_blue'
format = '[](fg:neutral_blue)[$symbol]($style)'

[os.symbols]
Arch = " "
Gentoo = " "
Linux = " "
NixOS = " "
Raspbian = " "
Void = "  "
Windows = " "

[character]
disabled = false
success_symbol = '[λ](bold green) '
error_symbol = '[λ](bold red) '

[time]
disabled = false
format = '[  $time]($style) '
time_format = '%R'
utc_time_offset = 'local'

[cmd_duration]
min_time = 10
show_milliseconds = false
style = 'bold yellow'
format = '[$duration](bold yellow)'

[git_branch]
symbol = ' '
style = 'bold purple'
truncation_length = 22
truncation_symbol = '…'
format = '[$symbol$branch(:$remote_branch)]($style) '	

[git_commit]
commit_hash_length = 7
tag_symbol = '󰓹 ' 
only_detached = false
tag_disabled = false
style = 'bold fg:dark1'
format = '[$tag\($hash\)]($style)'

[git_status]
style = "bold italic bg:dark1"
format = "([$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed]($style))"
conflicted = "[◪◦$count](italic bright-magenta)"
ahead = "[▴[$count](bold white)│](italic green)"
behind = "[▿[$count](bold white)│](italic red)"
diverged = "[◇ ▴$ahead_count(regular white)▿$behind_count](regular white)](italic bright-magenta)"
untracked = "[◌◦$count](italic bright-yellow)"
stashed = "[◃◈$count](italic white)"
modified = "[●◦$count](italic yellow)"
staged = "[▪[$count](bold white)│](italic bright-cyan)"
renamed = "[◎◦$count](italic bright-blue)"
deleted = "[✕$count](italic red)"

[status]
disabled = false
style = "bold fg:light0_soft bg:dark0_soft"
symbol = ' '
success_symbol = ' '
not_executable_symbol = ' '
not_found_symbol =  ' '
sigint_symbol = ' '
signal_symbol = ' '
map_symbol = true
format = '[$symbol$common_meaning $status $signal_name $signal_number]($style)'

[directory]
read_only = ""
fish_style_pwd_dir_length = 2
style = 'bold fg:fg0 bg:bg2'
read_only_style = 'bold fg:light0_soft bg:neutral_blue'
format = '[$read_only($read_only_style)$path]($style)'	
