"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$shell\
$directory\
$git_branch\
$git_commit\
$git_status\
$fill\
$cmd_duration\
$python\
$time\
$status
$character
"""
palette = 'mytilus_light'

[palettes.'mytilus_light']
fg            = '#2D2C37'
bg            = '#EEF0E1'
black       = '#55535F'
white       = '#555649'
red           = '#784153'
green         = '#415F30'
yellow        = '#665217'
blue          = '#435281'
magenta       = '#654773'
cyan          = '#0F5E76'
bg_red     = '#E9A8BB'
bg_green   = '#A7C995'
bg_yellow  = '#D1BC81'
bg_blue    = '#A9BBF2'
bg_magenta = '#D1AEE1'
bg_cyan    = '#83C9E4'

[python]
disabled       = false
symbol         = " "
version_format = '${raw}'
style          = 'bold fg:bg bg:black'
format         = '[ [$symbol](fg:bg bg:black)${version} (\($virtualenv\)) ]($style)'

[shell]
disabled       = false
bash_indicator = "bash"
zsh_indicator  = "%"
nu_indicator   = ">"
fish_indicator = ""
style          = 'bold fg:bg bg:fg'
format         = '[| $indicator ]($style)'

[fill]
symbol = ' '

[os]
disabled = false
style    = 'bold fg:bg bg:fg'
format   = '[ $symbol ]($style)'

[os.symbols]
Arch     = ""
Gentoo   = ""
Linux    = ""
NixOS    = ""
Raspbian = ""
Void     = ""
Windows  = ""

[character]
disabled       = false
success_symbol = '[λ](bold green) '
error_symbol   = '[λ](bold red) '

[time]
disabled        = false
format          = '[  $time |]($style)'
style           = 'bold fg:bg bg:fg'
time_format     = '%R'
utc_time_offset = 'local'

[cmd_duration]
min_time          = 0
show_milliseconds = true
style             = 'bold fg:bg bg:black'
format            = '[ $duration |]($style)'

[git_branch]
symbol            = ' '
style             = 'bold fg:bg bg:black'
truncation_length = 22
truncation_symbol = '…'
format            = '[| $symbol$branch(:$remote_branch)]($style)'

[git_commit]
commit_hash_length = 7
tag_symbol         = '󰓹 '
only_detached      = false
tag_disabled       = false
style              = 'bold fg:bg_magenta bg:black'
format             = '[ $tag\($hash\)]($style)'

[git_status]
format      = "[$ahead_behind$all_status ](fg:bg bg:black)"
diverged    = "[  $ahead_count $behind_count](fg:bg_magenta bg:black)"
ahead       = "[  $count](fg:bg_blue bg:black)"
behind      = "[  $count](fg:bg_red bg:black)"
conflicted  = "[ 󰵖 $count](fg:bg_red bg:black)"
stashed     = "[ 󰦕 $count](fg:bg_cyan bg:black)"
deleted     = "[  $count](fg:bg_red bg:black)"
renamed     = "[  $count](fg:bg_blue bg:black)"
modified    = "[  $count](fg:bg_cyan bg:black)"
typechanged = "[ 󰴝 $count](fg:bg_blue bg:black)"
staged      = "[ 󰗡 $count](fg:bg_green bg:black)"
untracked   = "[ ◌ $count](fg:bg_blue bg:black)"

[status]
disabled              = false
style                 = 'bold fg:bg bg:fg'
symbol                = ' '
success_symbol        = ' '
not_executable_symbol = ' '
not_found_symbol      = ' '
sigint_symbol         = ' '
signal_symbol         = ' '
map_symbol            = true
format                = '[ $symbol$common_meaning$status$signal_name$signal_number ]($style)'

[directory]
read_only                 = " "
fish_style_pwd_dir_length = 2
style                     = 'bold fg:bg bg:black'
read_only_style           = 'bold fg:bg bg:black'
format                    = '[ $read_only($read_only_style)$path ]($style)'
