"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$shell\
$directory\
$git_branch\
$git_commit\
$git_status\
$fill\
$cmd_duration\
$python\
$time\
$status
$character
"""
palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
fg0       = '#282828'
bg0       = '#f2e5bc'
bg2      = '#d5c4a1'
light3      = '#bdae93'
light4      = '#a89984'
neutral_red    = '#cc241d'
neutral_green  = '#98971a'
neutral_yellow = '#d79921'
neutral_blue   = '#458588'
neutral_purple = '#b16286'
neutral_aqua   = '#689d6a'
neutral_orange = '#d65d0e'
faded_red      = '#9d0006'
faded_green    = '#79740e'
faded_yellow   = '#b57614'
faded_blue     = '#076678'
faded_purple   = '#8f3f71'
faded_aqua     = '#427b58'
faded_orange   = '#af3a03'

[python]
disabled = false
symbol = " "
version_format = '${raw}'
style = 'bold fg:fg0 bg:bg2'
format = '[ [$symbol](fg:neutral_yellow bg:bg2)${version} (\($virtualenv\)) ]($style)'

[shell]
disabled = false
bash_indicator = "bash"
zsh_indicator = "%"
nu_indicator = ""
style = 'bold fg:fg0 bg:neutral_blue'
format = '[| $indicator ]($style)'	

[fill]
symbol = ' '

[os]
disabled = false
style = 'bold fg:fg0 bg:neutral_blue'
format = '[ $symbol ]($style)'

[os.symbols]
Arch = ""
Gentoo = ""
Linux = ""
NixOS = ""
Raspbian = ""
Void = ""
Windows = ""

[character]
disabled = false
success_symbol = '[λ](bold green) '
error_symbol = '[λ](bold red) '

[time]
disabled = false
format = '[  $time |]($style)'
style = 'bold fg:fg0 bg:neutral_blue'
time_format = '%R'
utc_time_offset = 'local'

[cmd_duration]
min_time = 0
show_milliseconds = true
style = 'bold fg:fg0 bg:bg2'
format = '[ $duration |]($style)'

[git_branch]
symbol = ' '
style = 'bold fg:fg0 bg:bg2'
truncation_length = 22
truncation_symbol = '…'
format = '[| $symbol$branch(:$remote_branch)]($style)'	

[git_commit]
commit_hash_length = 7
tag_symbol = '󰓹 ' 
only_detached = false
tag_disabled = false
style = 'bold fg:fg0 bg:bg2'
format = '[ $tag\($hash\)]($style)'

[git_status]
style = 'bold fg:fg0 bg:bg2'
format = "[$ahead_behind$all_status](fg:fg0 bg:bg2)"
diverged = "[  $ahead_count $behind_count](fg:fg0 bg:bg2)"
ahead = "[  $count](fg:fg0 bg:bg2)"
behind = "[  $count](fg:fg0 bg:bg2)"
conflicted = "[ 󰵖 $count](fg:fg0 bg:bg2)"
stashed = "[ 󰦕 $count](fg:fg0 bg:bg2)"
deleted = "[  $count](fg:fg0 bg:bg2)"
renamed = "[  $count](fg:fg0 bg:bg2)"
modified = "[  $count](fg:fg0 bg:bg2)"
typechanged = "[ 󰴝 $count](fg:fg0 bg:bg2)"
staged = "[ 󰗡 $count](fg:fg0 bg:bg2)"
untracked = "[ ◌ $count](fg:fg0 bg:bg2)"

[status]
disabled = false
style = 'bold fg:fg0 bg:neutral_blue'
symbol = ' '
success_symbol = ' '
not_executable_symbol = ' '
not_found_symbol =  ' '
sigint_symbol = ' '
signal_symbol = ' '
map_symbol = true
format = '[ $symbol$common_meaning$status$signal_name$signal_number ]($style)'

[directory]
read_only = " "
fish_style_pwd_dir_length = 2
read_only_style = 'bold fg:fg0 bg:bg2'
style = 'bold fg:fg0 bg:bg2'
format = '[ $read_only($read_only_style)$path ]($style)'	
