[colors]
foreground= '#EEF0DA'
background= '#161322'
ansi = [
    '#EEF0DA',
    '#BC778C',
    '#779B63',
    '#A48C4A',
    '#798CC6',
    '#A47EB5',
    '#4A9AB8',
    '#CDCAE0',
]
brights = [
    '#CDD0BA',
    '#BC778C',
    '#779B63',
    '#A48C4A',
    '#798CC6',
    '#A47EB5',
    '#4A9AB8',
    '#161322',
]
compose_cursor = '#B6BFBF'
cursor_bg = '#B6BFBF'
cursor_border = '#B6BFBF'
cursor_fg = '#2A2E32'
scrollbar_thumb = '#B6BFBF'
selection_bg = '#322B2C'
selection_fg = '#C1BCB6'
split = '#322B2C'

[colors.indexed]

[colors.tab_bar]
background = '#2A2E32'

[colors.tab_bar.active_tab]
bg_color = '#A56A8F'
fg_color = '#322B2C'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#B6BFBF'
fg_color = '#322B2C'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#B6BFBF'
fg_color = '#48906F'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#B6BFBF'
fg_color = '#368CA6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#B6BFBF'
fg_color = '#368CA6'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = 'even dark'
