[colors]
background = '#EEF0DA'
foreground = '#161322'
ansi = [
    '#161322',
    '#8C4C61',
    '#4C6E38',
    '#77601B',
    '#4F5F96',
	'#765286',
    '#116D89',
    '#EEF0DA',
]
brights = [
    '#2D2C32',
    '#8C4C61',
    '#4C6E38',
    '#77601B',
    '#4F5F96',
	'#765286',
    '#116D89',
    '#EEF0DA',
]
compose_cursor = '#2D2E28'
cursor_bg = '#2D2E28'
cursor_border = '#2D2E28'
cursor_fg = '#EEF0DA'
scrollbar_thumb = '#2D2C32'
selection_bg = '#2D2E28'
selection_fg = '#EEF0DA'
split = '#2D2C32'

[colors.indexed]

[colors.tab_bar]
background = '#2D2C32'

[colors.tab_bar.active_tab]
bg_color = '#AEC3B6'
fg_color = '#161322'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#CBBAA9'
fg_color = '#161322'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#CBBAA9'
fg_color = '#4C6E38'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#AFBFD0'
fg_color = '#161322'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#AFBFD0'
fg_color = '#4C6E38'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = 'even light'
